version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: koriddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

# docker compose -f docker-compose.migrations.yml up -d
#   lub docker compose -f docker-compose.migrations.yml ps 
# $env:ConnectionStrings__koriddb = "Host=localhost;Port=5432;Database=koriddb;Username=postgres;Password=postgres"
# dotnet ef migrations add InitialCreate --project .\KorID.Data\KorID.Data.csproj
# dotnet ef migrations add InitialCreate --project ./KorID.Data/KorID.Data.csproj